behaviors: {}
checkpoint_settings: {force: false, inference: false, initialize_from: null, load_model: false,
  resume: false, run_id: MyFirstAI, train_model: false}
debug: false
default_settings: null
engine_settings: {capture_frame_rate: 60, height: 84, no_graphics: false, quality_level: 5,
  target_frame_rate: -1, time_scale: 20, width: 84}
env_settings: {base_port: 5005, env_args: null, env_path: null, num_envs: 1, seed: -1}
environment_parameters: null
